project:
  type: website
  output-dir: docs

website:
  title: "E's Website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



